volumes:
  doi_portal_local_postgres_data: {}
  doi_portal_local_postgres_data_backups: {}
  doi_portal_local_redis_data: {}
  doi_portal_local_clamav_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: doi_portal_local_django
    container_name: doi_portal_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - /app/.venv
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: doi_portal_production_postgres
    container_name: doi_portal_local_postgres
    volumes:
      - doi_portal_local_postgres_data:/var/lib/postgresql/data
      - doi_portal_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: doi_portal_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:7.2
    container_name: doi_portal_local_redis
    volumes:
      - doi_portal_local_redis_data:/data

  clamav:
    image: clamav/clamav:latest
    container_name: doi_portal_local_clamav
    ports:
      - "3310:3310"
    volumes:
      - doi_portal_local_clamav_data:/var/lib/clamav
    restart: unless-stopped

  celeryworker:
    <<: *django
    image: doi_portal_local_celeryworker
    container_name: doi_portal_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
      - clamav
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: doi_portal_local_celerybeat
    container_name: doi_portal_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: doi_portal_local_flower
    container_name: doi_portal_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
